project:
  type: website
  output-dir: docs

resources:
  - CNAME

website:
  title: "monographs"
  site-url: https://syrchanan.quarto.pub/
  description: "A collection of various short studies"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/syrchanan
      - icon: globe
        href: https://www.connorhanan.com
      - icon: twitter
        href: https://twitter.com/ConnorHanan
    left:
      - icon: rss
        href: blog.xml
  favicon: ./images/favicon.png
format:
  html:
    theme: lux
    css: styles.css