project:
  type: website
  output-dir: docs

resources:
  - CNAME

website:
  title: "monographs"
  site-url: https://www.blog.connorhanan.com/
  description: "A collection of various short studies"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/syrchanan
      - icon: globe
        href: https://www.connorhanan.com
      - icon: linkedin
        href: https://www.linkedin.com/in/connorhanan/
    left:
      - icon: rss
        href: index.xml
  favicon: ./images/favicon.png
format:
  html:
    theme: lux
    css: styles.css