---
title: "The Definitive Ranking of California Burritos"
subtitle: "The Best and Where to Get Them"
date: "2023-09-10"
image: "./vallartas.jfif"
categories:
  - Food
  - Ranking
draft: false
---

### What Are They?

California burritos are very near and dear to me - if I go to a Mexican restaurant, I will undoubtedly get their version of a California burrito. No matter where I am, it's always a great benchmark to compare against other restaurants.

What is defining feature of the California burrito? Fries.

Adding fries to a burrito elevates it to a whole other level; standard burritos just can't compare. Add in the rest of your favorite toppings, and you have a wonderful burrito in your hands - but it all starts with the fries.

It must also be noted that a classic California burrito will have carne asada as the meat. Other versions do exist (for example, replacing the carne asada with chicken makes it an Arizona burrito), but none can compete with a perfectly executed California burrito.

### The Rankings

All that to say, there are very important things that can separate one California burrito from another.

Without further ado, here are my rankings for best California burritos I have ever had:

1.  Alejandro's (Carlsbad, CA) - CLOSED
2.  Vallarta's (Carlsbad, CA)
3.  The Taco Stand (Encinitas, CA)
4.  Electric Burrito (New York City, NY)
5.  Roberto's (Carlsbad, CA)
6.  Cessy's (Carlsbad, CA) - CLOSED

------------------------------------------------------------------------

If you ever get a chance, seek out one of the above locations - or even make one yourself. I can all but guarantee that you won't be disappointed.

-CH
